name: snakemake
channels:
  - dnachun
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohttp=3.9.3=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - bcrypt=4.1.2=py310hcb5633a_0
  - boto3=1.34.87=pyhd8ed1ab_0
  - botocore=1.34.87=pyge310_1234567_0
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.10=haf5fa05_0
  - coin-or-utils=2.11.11=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=42.0.5=py310h75e40e8_0
  - datrie=0.8.2=py310h2372a71_7
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.21.1=pyhd8ed1ab_0
  - dpath=2.1.6=pyha770c72_0
  - dropbox=11.36.2=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - filechunkio=1.8=py_2
  - filelock=3.13.4=pyhd8ed1ab_0
  - frozenlist=1.4.1=py310h2372a71_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - google-api-core=2.18.0=pyhd8ed1ab_0
  - google-api-python-client=2.126.0=pyhd8ed1ab_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_0
  - google-cloud-core=2.4.1=pyhd8ed1ab_0
  - google-cloud-storage=2.16.0=pyhca7485f_0
  - google-crc32c=1.1.2=py310hc5c09a0_5
  - google-resumable-media=2.7.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.63.0=pyhd8ed1ab_0
  - grpcio=1.62.2=py310h1b8f574_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - libgrpc=1.62.2=h15f2491_0
  - liblapack=3.9.0=22_linux64_openblas
  - liblapacke=3.9.0=22_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.3=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - logmuse=0.2.6=pyh8c360ce_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - multidict=6.0.5=py310h2372a71_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - numpy=1.26.4=py310hb13e2d6_0
  - oauth2client=4.1.3=py_0
  - openssl=3.2.1=hd590300_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py310hcc13569_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - peppy=0.40.1=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prettytable=3.10.0=pyhd8ed1ab_0
  - proto-plus=1.23.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py310ha8c1f0e_0
  - psutil=5.9.8=py310h2372a71_0
  - pulp=2.7.0=py310hff52083_1
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h2372a71_3
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.1.1=pyhd8ed1ab_0
  - python=3.10.14=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-irodsclient=2.0.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rpds-py=0.18.0=py310hcb5633a_0
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.10.1=pyhd8ed1ab_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - setuptools-scm=8.0.4=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=7.0.4=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=7.15.2=hdfd78af_0
  - snakemake-minimal=7.15.2=pyhdfd78af_0
  - stone=3.3.3=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ubiquerg=0.7.0=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.16.0=py310h2372a71_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - yte=1.5.4=pyha770c72_0
  - zipp=3.17.0=pyhd8ed1ab_0
prefix: /home/maurertm/micromamba/envs/snakemake
